### ISSUE TITLE
Wrong parameter in operator.yaml

### ISSUE THREAD

**Issue by quemilk** [AzulSystems/opthub-helm-charts#1]
I think it wrong   in operator.yaml
- -Dbroker.compilation-parallelism={{ .Values.compilations.parallelism.lookupParallelism }}

It shoud be 

- -Dbroker.compilation-parallelism={{ .Values.compilations.parallelism.limitPerCompileBroker }}

**Comment by vladykin** [comment]
This is intended, there is no mistake in that line.
